name: angular-app

on:
  push:
    branches: 
       - 
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v3
    - name: use node js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install 
      run: |
        npm install
        sudo apt install nodejs
    - name: make zip file 
      run: |
        zip admin.zip */  
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: admin.zip
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: package
      - name: SSH deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          port: ${{secrets.PORT}}
          source: "admin.zip"
          target: "/var/www/html/angular-app/"
          run: |
            sudo unzip admin.zip
            pm2 start app.js
